const types = {
  SET_BREEDS_LIST: 'SET_BREEDS_LIST',
  SEARCH_BREED: 'SEARCH_BREED',
  SET_APP_READY_STATE: 'SET_APP_READY_STATE',
  HANDLE_IMAGE_IN_FAVORITES: 'HANDLE_IMAGE_IN_FAVORITES',
  SET_FAVORITES_FROM_CACHE: 'SET_FAVORITES_FROM_CACHE'
};

export default types;
